# Numpy Tutorial

In [3]:
# Run some setup code for this notebook.

import random
import numpy as np
import sys
sys.path.append('/Users/ibabic/workspace/cs231n')
from assignment1.cs231n.data_utils import load_CIFAR10
import matplotlib.pyplot as plt

from __future__ import print_function

# This is a bit of magic to make matplotlib figures appear inline in the notebook
# rather than in a new window.
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [16]:
# Load the raw CIFAR-10 data.
cifar10_dir = '/Users/ibabic/workspace/cs231n/assignment1/cs231n/datasets/cifar-10-batches-py'
X_train, y_train, X_test, y_test = load_CIFAR10(cifar10_dir)

# As a sanity check, we print out the size of the training and test data.
print('Training data shape: ', X_train.shape)
print('Training labels shape: ', y_train.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', y_test.shape)

Training data shape:  (50000, 32, 32, 3)
Training labels shape:  (50000,)
Test data shape:  (10000, 32, 32, 3)
Test labels shape:  (10000,)


In [21]:
X_train = np.reshape(X_train,(X_train.shape[0], -1))


In [26]:
X_train[1]**2

array([ 23716.,  31329.,  34969., ...,  20449.,  17689.,  20736.])

In [24]:
32*32*3 

3072

In [ ]:
# Visualize some examples from the dataset.
# We show a few examples of training images from each class.
classes = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
num_classes = len(classes)
samples_per_class = 7
y, cls in enumerate(classes):
    idxs = np.flatnonzero(y_train == y)
    idxs = np.random.choice(idxs, samples_per_class, replace=False)
    for i, idx in enumerate(idxs):
        plt_idx = i * num_classes + y + 1
        plt.subplot(samples_per_class, num_classes, plt_idx)
        plt.imshow(X_train[idx].astype('uint8'))
        plt.axis('off')
        if i == 0:
            plt.title(cls)
plt.show()

In [80]:
x = np.array([5, 2, 7, 1, -2, 3]) # example data
print(x)
k = 2 # return the indices of the 2 smallest values
np.argsort(x, axis=-1)[:k]

[ 5  2  7  1 -2  3]


array([4, 3])

In [74]:
np.argsort(x)

array([[1, 0, 2],
       [1, 0, 2]])

In [66]:
x.shape

(2, 3)

In [10]:
x = np.array([[1, 1, 1, 1, 1, 1],[2, 2, 2, 2, 2, 2],[3, 3, 3, 3, 3, 3]])
y = np.array([[10, 10, 10, 10, 10, 10],[20, 20, 20, 20, 20, 20]])

In [11]:
print(x.shape, y.shape)

(3, 6) (2, 6)


In [28]:
np.sqrt(np.sum((x[:, np.newaxis, :] - y)**2, -1))[0][1]

46.540305112880382

In [25]:
(((-19)**2)*6)**0.5

46.54030511288038

In [67]:
print(np.sum(x, axis=1).shape, np.sum(y, axis=1).shape)

(3,) (2,)


In [61]:
lala = np.dot(x,y.T)
print(lala)

[[ 60 120]
 [120 240]
 [180 360]]


In [69]:
lala + np.sum(y, axis=1)

array([[120, 240],
       [180, 360],
       [240, 480]])

In [60]:
x + lala

ValueError: operands could not be broadcast together with shapes (3,6) (3,2) 

In [53]:
something = np.array([100,200, 300]) 
print(something.shape)

(3,)


In [55]:
 something[:, np.newaxis] + lala

array([[160, 220],
       [320, 440],
       [480, 660]])

In [4]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]]) 
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [5]:
a

array([[1],
       [2],
       [3]])

In [6]:
b

array([[2],
       [3],
       [4]])

In [7]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])